# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-06 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0013_cuotaextraordinaria_cuotaextraunidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abono',
            name='detalle',
        ),
        migrations.AddField(
            model_name='abono',
            name='recibo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pagos.Recibo'),
            preserve_default=False,
        ),
    ]
